### 1-1 Import sales CSV file into a dataframe:

In [55]:
import pandas as pd
df = pd.read_csv('retail_sales_dirty_dataset.csv')
display(df.head(10))

,order_id,date,region,product,salesperson,channel,quantity,price,sales,cost,notes,irrelevant_column
0,10000,2024-11-23,South,Widget E,Grace,Online,8,48.53,388.24,298.26,ok,extra2
1,10001,2024-12-25,EAST,Widget C,Eva,Online,19,59.25,1125.75,939.61,ok,extra14
2,10002,2024-11-05,SOUTH,Widget E,David,Wholesale,15,109.56,1643.4,1456.97,ok,extra5
3,10003,2024-02-21,South,Widget E,Carol,Wholesale,12,36.72,440.64,254.53,ok,extra47
4,10004,2024-04-22,West,Widget E,Frank,Online,2,49.66,99.32,41.32,ok,extra42
5,10005,2024-10-14,west,Widget A,Alice,Online,14,180.08,2521.12,1511.92,ok,extra10
6,10006,2024-08-27,SOUTH,Widget A,Eva,Retail,1,137.66,137.66,62.95,ok,extra11
7,10007,2024-04-01,East,Widget E,Alice,Wholesale,10,169.13,1691.3,1105.83,ok,extra21
8,10008,2024-05-02,East,Widget B,Helen,Wholesale,3,21.70,65.1,41.86,ok,extra11
9,10009,2024-12-19,SOUTH,Widget A,David,Wholesale,12,NaN,1085.16,714.89,ok,extra15

### 1-2 Explore input data structure, null counts, number of rows, columns list and data types:

In [ ]:
print(df.info())

### 1-3 Missing Values Count:

In [ ]:
def missing_values_count(data_frame):
  """
    Returns the number of missing values by columns of a dataset
    that contain at least one missing value. 
  """
  missing_count = data_frame.isnull().sum()
  missing_count = missing_count[missing_count > 0 ]
  return missing_count

print("The number of missing values in each column are as follows:")
print(missing_values_count(df) )

The number of missing calues in each column are as follows:
region    25
price     28
sales     23
cost      27
dtype: int64

### 1-4 Identifying Invalid date Values:
##### before conerting "date" values from string to datetime, we should identify if there are invalid values to remove.

In [ ]:
df_invalid_dates = df[pd.to_datetime(df['date'],format ='mixed', errors='coerce').isna()]
print("Invalid dates entry (to be removed in data Cleaning stage)")
print(df_invalid_dates[['order_id','date','price']])

     order_id        date   price
18      10018  2024-13-40  189.28
29      10029  2024-13-40   63.23
203     10203  2024-13-40   49.12
256     10256  2024-13-40   78.99
258     10258  2024-13-40  102.42
520     10520  2024-13-40   26.58
858     10018  2024-13-40  189.28

### 1-5 Identifying invalid quantity, price, sales, and cost values:

In [ ]:
def unexpected_negative_values(data_frame , column_name):
  
 df_invalid_negative_val =  data_frame.loc[data_frame[column_name] <0 ,['order_id','date','quantity','price','sales','cost']] 
 return df_invalid_negative_val 

print("\n Rows ewith invalid negative price values:\n")
unexpected_negative_values(df,'price')

print("\n Rows with invalid negative price values:\n")
unexpected_negative_values(df,'price')

print("\n Rows with invalid negative price values:\n")
unexpected_negative_values(df,'price')

print("\n Rows with invalid negative price values:\n")
unexpected_negative_values(df,'price')

 Rows eith invalid negative price values:

     order_id        date  quantity   price    sales     cost
15      10015  2024-06-09        10  -94.16    941.6   814.02
62      10062  2024-04-16         8  -69.07      NaN      NaN
134     10134  2024-02-12         5 -149.23   746.15   416.60
195     10195  2024-12-12        17   -8.91   151.47   119.68
280     10280  2024-04-19         9  -75.20    676.8   423.81
287     10287  2024-02-13        20 -185.71   3714.2  3099.04
290     10290  12/30/2024        17  -64.46  1095.82   706.77
330     10330  2024-12-10        11 -137.16  1508.76  1352.77
417     10417  2024-11-06        16  -64.21  1027.36   518.53
433     10433  2024-09-24         1  -28.46    28.46    24.71
444     10444  2024-05-20        18 -124.82  2246.76  1663.37
491     10491  2024-07-03         2 -195.18   390.36   326.55
532     10532  2024-11-16         8 -147.44  1179.52   636.76
589     10589  2024-06-20        18  -55.18   993.24   638.90
772     10772  2024-12-02        18  -11.12   200.16   167.34
855     10015  2024-06-09        10  -94.16    941.6   814.02

## 2 - Data Cleaning
#### In this section we will clean data, removing irrevelant columns, handling missing info, removing rows with invalid data, etc.

### 2-1 Removing Irrevelant Columns:

In [ ]:
## there is a column irrelevant_column which its values have no business value. We will not use this column in any analysis.
df.drop(columns=['irrelevant_column'], inplace = True)
display(df.head(10))